- README.md
- src/index.ts
- by default, instrument will be on; env will not take any effect in this case
- when `requireEnv` is not set, it will be assumed to be `false`
So after `2.1.0`, the only chance that to disable the plugin is to
- set `requireEnv` === true AND `VITE_COVERAGE=false`.
> fix: correct logic of requireEnv

- src/index.ts
by default babel transform will load the user's babel config, which may cause issues, e.g., transform the file into cjs modules instead of esm.
A relevant issue in vite:
https://github.com/vitejs/vite/pull/2766/files
> fix: should ignore user provided babel configs

- README.md
- package.json
- src/index.ts
- src/types.d.ts
- tsconfig.json
- yarn.lock
Hello @iFaxity 
I was trying to get coverage for https://github.com/elevatebart/calc-vite and found your plugin.
It is really good.
I did a bit of house cleaning in devDependencies to simplify the life of most vite users who don't have babel installed.
I also made sure that the plugin is run last so that it is never running directly on SFC components but on their JS transformed version. It's OK to do that since we can rely on sourceMaps.
> fix: use a strict typescript and make the plugin a post

- README.md
- src/index.ts
Allow support for instrument in build mode.
This is usefull when you run cypress in e2e mode for example.
> feat: Support instrument in build mode

- README.md
Updated documentation for `requireEnv` in order to better explain e.g how it relates to the `cypress` flag.
> docs: Updated documentation on requireEnv

- README.md
- src/index.ts
Better documentation over the behavior of the automatic enabling of `build.sourcemap` for the plugin to generate better code coverage
> fix: Docs for automatic sourcemapping

- src/index.ts
Fixes #17, loading CYPRESS_COVERAGE from process.env instead of Vite env.
> fix: Load CYPRESS_COVERAGE from process.env

- src/index.ts
Replaced reference id with this.getFileName() to get accurate filenames for the code coverage
> fix: #23 Fix asset filenames

- package-lock.json
- package.json
- src/index.ts
Fixes #31 by replacing chalk with picocolors. As Chalk v5 only supports ESM modules and not CJS anymore.
Chalk v4 is a rather large library so this also improves build size.
> feat: Replaced chalk with picocolors

- src/index.ts
This PR fixes it for me; alternatively: Is there a way to pass options directly to the Istanbul plugin?
cf. https://github.com/kategengler/ember-cli-code-coverage/issues/214#issuecomment-619398136 :
> By default istanbul injects a new Function('return this') into the source code to get the global object. This violates a strict CSP. It has been reported and fixed upstream some time ago by adding the additional configuration option coverageGlobalScopeFunc. If it's set to false the eval will not be used. Instead it directly uses the value of coverageGlobalScope. This defaults to this but could be changed to global. See the merge request for details: https://github.com/istanbuljs/istanbuljs/pull/200
> Fix for: Instrumentation fails if CSP 'unsafe-eval' is not set

- src/index.ts
I believe this should fix https://github.com/iFaxity/vite-plugin-istanbul/issues/46, this is how `picocolors` is [supposed](https://github.com/alexeyraspopov/picocolors/issues/48#issuecomment-1180497495) to be used.
If I'm not mistaken, there are no contribution guidelines in this repo, so please let me know if there's something I missed.
I tested this fix in the following way in the `next`branch using Node v16.16.0:
```
npm run build
node dist/index.mjs
```
Without this fix, an error is thrown:
```
file:///.../vite-plugin-istanbul/dist/index.mjs:5
import { yellow } from 'picocolors';
^^^^^^
SyntaxError: Named export 'yellow' not found. The requested module 'picocolors' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported …
```
> fix: use picocolors correctly

- src/index.ts
- src/types.d.ts
`loadNycConfig` is async:
https://github.com/istanbuljs/load-nyc-config/blob/2033a007672d90669c48c79e6a2d63a3cd0851a7/index.js#L139-L164
But, it's handled as if it's a synchronous one. So, `nycrc` isn't being loaded or respected correctly.
> fix: Correctly load nycrc

- src/index.ts
If `build.sourcemap` is set to `true` in vite config, `testExclude` is not properly initialized and the call `testExclude.shouldInstrument` in `transform` raises an exception.
> Fix exception that can occur if build.sourcemap is set to true in vite config

- src/index.ts
Pruning the query string from the transform ID of Vue files to get the actual filename.
An attempt to fix #67, but might need further improvements to avoid clashing with other plugins.
> fix: Pruned querystring of Vue files in serve mode

- package-lock.json
- package.json
- src/index.ts
- src/source-map.ts
- src/types.d.ts
fix: #101
Currently, this plugin returns the source map combined with the source maps of all previous plugins.
This means that the source maps are combined twice because they are also combined outside the plugins later ([here](https://github.com/vitejs/vite/blob/b70e7831e8f60e4449cfbe902838cc9ca4a56847/packages/vite/src/node/server/pluginContainer.ts#L775)), which leads to incorrect line numbers.
This PR changes to call `instrumenter.instrumentSync` twice to create the source map and the instrumented code separately.
> fix: Fix source map

- src/source-map.ts
Thank you for releasing [v5.0.0-rc.1](https://github.com/iFaxity/vite-plugin-istanbul/releases/tag/v5.0.0-rc.1)!
I'm trying it in my projects to confirm #101 is now resolved, but found a little bug.
As I stated [here](https://github.com/iFaxity/vite-plugin-istanbul/pull/113#discussion_r1227558842), we create an identity source map to ensure the 1st and the 2nd instrumented codes have the same number of lines. More precisely, the identity source map and the source map obtained by `this.getCombinedSourcemap()` must have the same number of entries, otherwise the final source map will have incorrect line numbers.
This PR removes the unneeded `file` entry from an identity source map.
```javascript
inputSourceMap: {
version: 3,
mappings: "AA2BI,mBAGM,cAHN;;;;;;;;;...",
names: ["useEffect", …
```
> fix: Remove unneeded entry from an identity source map

- src/index.ts
- src/source-map.ts
Hi @iFaxity,
In PR #115, we have removed the `file` field in the identity source map because I thought combined source maps from previous plugins do not have it. However, I found it is not always true.
The `file` field of a combined source map is added [here](https://github.com/vitejs/vite/blob/fd1b7315852616a00156f79b413c0f2a0029e51b/packages/vite/src/node/utils.ts#L798) in `combineSourcemaps` function. Below is the call tree from `this.getCombinedSourcemap`.
- [`TransformContext.getCombinedSourcemap`](https://github.com/vitejs/vite/blob/fd1b7315852616a00156f79b413c0f2a0029e51b/packages/vite/src/node/server/pluginContainer.ts#L589)
- [`TransformContext#_getCombinedSourcemap`](https://github.com/vitejs/vite/blob/fd1b7315852616a00156f79b413c0f2a0029e51b/packages/vite/src/node/server/pluginC …
> fix: Ensure identity source map has the same number of fields as the combined source map

- package.json
Removed node from engines specification to prevent error on install.
Fixes #214.
> fix: removed engine version

- README.md
- package.json
- pnpm-lock.yaml
- src/index.ts
- src/types.d.ts
hey! I recently had an issue with my instrumented code failing tests and found out that Babel was transforming our json imports incorrectly. I thought I'd open a PR to add
```ts
generatorOpts: {
importAttributesKeyword: 'with'
}
```
to the `createInstrumenter` options, but ended up with this one which is more generic. WDYT?
(happy new year!)
> feat: allow passing generatorOpts down to Babel

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Updated build workflows/pipelines to setup pnpm before setting up node. As the setup-node step requires that pnpm is already installed.
> build(ci): updated build to setup pnpm before node
